const light = {
  font: {
    family: {
      light: 'WeTheCurious-Light, Arial, sans-serif',
      regular: 'WeTheCurious-Regular, Arial, sans-serif',
      bold: 'WeTheCurious-Bold, Arial, sans-serif',
      heavy: 'WeTheCurious-Heavy, Arial, sans-serif',
    },
    weight: {
      light: 100,
      regular: 400,
      bold: 700,
      heavy: 900,
    },
  },
  radius: {
    topLeft: '0.0em 1.25em 1.25em 1.25em',
    topRight: '1.25em 0.0em 1.25em 1.25em',
    bottomRight: '1.25em 1.25em 0.0em 1.25em',
    bottomLeft: '1.25em 1.25em 1.25em 0.0em',
  },
  color: {
    brandColor: '#259b8e',
    neutralColorPrimary: '#433a34',
    neutralColorSecondary: '#f0f0f0',
    accentColorPrimary: '#259b8e',
    accentColorSecondary: '#008fd0',
    linkColor: '#259b8e',
    statusColorCritical: '#e0322a',
    statusColorError: '#e0322a',
    statusColorWarning: '#ea7424',
    statusColorOk: '#29aeaf',
    statusColorUnknown: '#919191',
    statusColorDisabled: '#f0f0f0',
    greyColorPrimary: '#58504a',
    greyColorSecondary: '#6b6764',
    greyColorTertiary: '#949290',
    greyColorQuaternary: '#bebdbc',
    greyColorQuinary: '#e9e9e9',
    textColor: '#58504a',
    textColorHeading: '#58504a',
    textColorH1: '#58504a',
    textColorH2: '#58504a',
    textColorH3: '#58504a',
    textColorH4: '#58504a',
    textColorH5: '#58504a',
    textColorH6: '#58504a',
    inverseTextColor: 'white',
    inverseTextColorHeading: 'white',
    inverseTextColorH1: 'white',
    inverseTextColorH2: 'white',
    inverseTextColorH3: 'white',
    inverseTextColorH4: 'white',
    inverseTextColorH5: 'white',
    inverseTextColorH6: 'white',
    inverseTextColorLabel: '#919191',
    inverseTextColorValue: 'white',
    imageOverlayText: 'white',
    imageOverlayGradient: 'rgba(0,0,0,0.6)',
  },
  modifiers: {
    hoverModifier: 'hsl(+30%, +10%, -15%)',
    disableModifier: 'black',
    attentionModifier: 'black',
    inactiveModifier: 'black',
  },
  backgroundColor: 'white',
}

export default light
